name: Build and Test NixOS Mach25 Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image:
    name: Build and Test Raspberry Pi Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64, linux/arm/v7

    - name: Build Docker Image
      run: |
        docker build -t mach25 \
          -f mach25/Dockerfile \
          --build-arg GOOS=linux \
          --build-arg GOARCH=arm \
          --build-arg RPI_VERSION=4 \
          .

    - name: Run Docker Container
      run: |
        mkdir -p output
        docker run --rm -v ${{ github.workspace }}/output:/output mach25

    - name: Upload SD Image Artifact
      uses: actions/upload-artifact@v3
      with:
        name: raspberry-pi-sd-image
        path: output/nixos-sd-image-*.img
